### ISSUE TITLE
Logic errors 

### ISSUE THREAD

**Issue by vasudevarao3** [iamwatchdogs/UnitConversion#2]
Hey shamith, I found that your code is displaying wrong outputs for inputs in Length and Temperature converter....

I will also try to test the other converters too.....If I found any errors or bugs in this mini project, I will inform you my friend....

**Comment by iamwatchdogs** [comment]
I have verified the issue and yes, there is an error in my unit conversion logic. Thank you for reporting... Will you try resolving the issue ?

**Comment by vasudevarao3** [comment]
Yes,I am interest to work on it.....I will try to resolve the issue

**Comment by iamwatchdogs** [comment]
Go ahead, I'm assigning you this issue. I'll check the code a bit later and come back to you
